apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Service.yaml

images:
- name: app-nofification
  newName: manscalh/app-nofification
  newTag: 73bc449b6f12487ec11d04a8c095c49315c3692f
- name: app-notification
  newName: manscalh/app-notification
  newTag: cecb738171a5326a6e0626bcaa98a5e4cf0dcc5d
