apiVersion: v1
kind: Service
metadata:
  name: app-nofification-service
spec:
  type: LoadBalancer
  selector:
    app: app-nofification
  ports:
  - port: 3002        #SERVICE URL
    targetPort: 3002  #CONTAINER
    # nodePort: 30001   #CLUSTER